service: chromeless-homepage

provider:
  name: aws
  runtime: nodejs6.10
  region: eu-west-1
  deploymentBucket: serverless-deployments-${env:AWS_REGION}-${env:AWS_ACCOUNT_ID}

plugins:
  - serverless-plugin-typescript
  - serverless-offline

package:
  excludeDevDependencies: false

functions:
  run:
    handler: handler.default
    memorySize: 128
    timeout: 30
    events:
      - http:
          path: /
          method: any
    environment:
      CHROMELESS_ENDPOINT_URL: ${env:CHROMELESS_ENDPOINT_URL}
      CHROMELESS_ENDPOINT_API_KEY: ${env:CHROMELESS_ENDPOINT_API_KEY}
      REDIS_HOST: ${env:REDIS_HOST}
      REDIS_PORT: ${env:REDIS_PORT}
      REDIS_PASSWORD: ${env:REDIS_PASSWORD}
      #DEBUG: chromeless

resources:
  Resources:

    RunLogGroup:
      Properties:
        RetentionInDays: 7
